#pragma once

//From glfw3.h
#define IRAD_MOUSE_BUTTON_1         0
#define IRAD_MOUSE_BUTTON_2         1
#define IRAD_MOUSE_BUTTON_3         2
#define IRAD_MOUSE_BUTTON_4         3
#define IRAD_MOUSE_BUTTON_5         4
#define IRAD_MOUSE_BUTTON_6         5
#define IRAD_MOUSE_BUTTON_7         6
#define IRAD_MOUSE_BUTTON_8         7
#define IRAD_MOUSE_BUTTON_LAST      IRAD_MOUSE_BUTTON_8
#define IRAD_MOUSE_BUTTON_LEFT      IRAD_MOUSE_BUTTON_1
#define IRAD_MOUSE_BUTTON_RIGHT     IRAD_MOUSE_BUTTON_2
#define IRAD_MOUSE_BUTTON_MIDDLE    IRAD_MOUSE_BUTTON_3
